Show Copied info when an identicon is clicked
ChainSafe/Multix pull request #101
Opened 2023-04-23 21:25 UTC by tarunsamanta2k20

Issue Description:
Input from users:

I don't understand why the cursor of the mouse has a "+" when it's hovering an identicon.

This is a behavior coming from the @polkadot/react-identicon icons. If clicked, the address of the account will be copied to the clipboard. Users need to know about this as it's hidden right now.

Proposal: show a "copied" tool-tip above or below the identicon when clicked. It should be visible for ~5 sec
Alternatively we could use a toast with the toast context useToasts

Fixes: i have added all the required component but don't know why it's not working.

2023-04-23 21:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafe/Multix?pullRequest=101) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafe/Multix?pullRequest=101) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafe/Multix?pullRequest=101) it.</sub>

2023-04-23 22:26 UTC, Tbaut requested changes
From my point of view, you are close to have something working.
Please make sure to type your props, this is TS, not JS.
also in terms of style, please have the `MultixIdenticon` props on a separate line for each (I left one comment but this is for all occurences).

2023-04-23 22:26 UTC, Tbaut commented on ui/package.json
> +    "react-tooltip": "^5.11.1",
you do not need to add either matrial-iu/core, nor react-tooltip.
Please remove them

2023-04-23 22:26 UTC, Tbaut commented on ui/src/components/AccountSelect/index.tsx
> +                  <MultixIdenticon value={account.address} theme="substrate" size={40} className={""} />
On several lines please, as it was for `Identicon`

2023-04-23 22:26 UTC, Tbaut commented on ui/src/components/MultixIdenticon.tsx
> +export default function MultixIdenticon({value,theme,size,className}) {
This is a typescript file, you must have types for the props.

2023-04-23 22:26 UTC, Tbaut commented on ui/src/components/MultixIdenticon.tsx
> +    <>
No need for this, the Tooltip only one component.

2023-04-24 10:04 UTC, Tbaut requested changes
Please make sure that:
- MultixIdenticon props are on new lines
- run `yarn lint` or `yarn lint --fix` and fix any error

2023-04-24 10:04 UTC, Tbaut commented on ui/package.json
> +    "@material-ui/core": "^4.12.4",
This is not needed, you should use
```
import Tooltip from '@mui/material/Tooltip';
```

2023-04-24 10:04 UTC, Tbaut commented on ui/src/components/MultixIdenticon.tsx
> +            ></Identicon>
```suggestion
            />
```

2023-04-24 10:04 UTC, Tbaut commented on ui/src/components/MultixIdenticon.tsx
> +    <div>
this `div` wrapper is not needed as far as I can tell, please remove.

2023-04-24 10:10 UTC, Tbaut commented on ui/src/components/MultixIdenticon.tsx
> +      <Tooltip
This adds a constant tooltip to the icon eventually. There is no notion of "appearing on click", or being invisible after a couple seconds. You need to take this into consideration.

2023-04-24 10:54 UTC, tarunsamanta2k20 commented
@Tbaut no onClick() found  for yarn add @polkadot/react-identicon.

2023-04-25 07:23 UTC, tarunsamanta2k20 commented
@Tbaut somehow i did. But for that I had to move the icon button along with Identicon. watch my demo once. 

https://user-images.githubusercontent.com/55488549/234203837-8ee0924d-7a59-41dc-aff1-099d144aafc9.mp4

2023-04-25 08:04 UTC, Tbaut commented
The video doesn't display for me. You need to wrap the identicon and catch the click there.

2023-04-25 08:15 UTC, tarunsamanta2k20 commented
> The video doesn't display for me. You need to wrap the identicon and catch the click there.

Please watch it on laptop or desktop

2023-04-25 20:48 UTC, Tbaut commented
The file is corrupt, the video can't be seen on anything for me.
![image](https://user-images.githubusercontent.com/33178835/234400115-b66dcb58-27b5-4c0c-869b-0269186105ec.png)

2023-04-26 01:28 UTC, tarunsamanta2k20 commented
@Tbautp Check my latest commit once

2023-04-26 04:14 UTC, tarunsamanta2k20 commented
> The file is corrupt, the video can't be seen on anything for me. ![image](https://user-images.githubusercontent.com/33178835/234400115-b66dcb58-27b5-4c0c-869b-0269186105ec.png)

@Tbaut i am watching this video without any issue.

2023-05-03 07:51 UTC, closed without merging

2023-05-03 07:53 UTC, Tbaut commented
This type of Ai assisted, low quality submissions will not be dealt with in the future. Thanks for the contributions.