Lykhoyda/refactor routes
ChainSafe/Multix pull request #111
Opened 2023-05-04 15:12 UTC by Lykhoyda

2023-05-08 15:00 UTC, Tbaut requested changes
Nice, thanks a lot. I've found a couple nits, but nothing more.

2023-05-09 12:54 UTC, Lykhoyda commented on packages/ui/src/App.tsx
> +import React from "react";
indeed it's not required anymore with a new React

2023-05-09 13:27 UTC, Lykhoyda commented on .yarn/releases/yarn-3.5.1.cjs
I think it was added by mistake to .yarnrc file:
```sh
yarnPath: .yarn/releases/yarn-3.5.1.cjs
```

So in the normal case, it shouldn't add the library to the .yarn/releases as it will take it from package.json packageManager

2023-05-10 08:43 UTC, Tbaut commented on packages/ui/src/App.tsx
>  import MainLayout from "./components/layout/Main";
```suggestion
import MainLayout from "./components/layout/Main";

```

2023-05-10 08:43 UTC, Tbaut commented on .yarn/releases/yarn-3.5.1.cjs
The gitignore has an exception for releases https://github.com/ChainSafe/Multix/blob/main/.gitignore#L120
This should be removed I believe.

I didn't research this part at all, yarn upgraded somehow on my machine and added the new binary there. If you remove it, then we should also delete it from the gitignore.

also it's used in the dockerfile, where it should be removed https://github.com/ChainSafe/Multix/blob/main/Dockerfile#L12

2023-05-10 09:46 UTC, Lykhoyda commented on .yarn/releases/yarn-3.5.1.cjs
@Tbaut updated

2023-05-10 11:24 UTC, Tbaut requested changes
`ADD .yarn/releases .yarn/releases` needs to be removed, it doesn't build the images for me otherwise.

2023-05-10 12:32 UTC, Tbaut approved these changes
Looks good to go, thanks a lot!

2023-05-10 12:32 UTC, merged