Add accordion to settings page
ChainSafe/Multix pull request #361
Opened 2023-09-22 13:11 UTC by Lykhoyda

Closes #336 
- Update UI of the Settings page (Watched account and Wallet connect)
- Watched accounts moved from components to the Settings page folder (as used now only in one place)
- Feature to expand accordion using hashtags #watched-acccounts and #wallet-connect

! 
There is no Wallet connect design yet

2023-09-22 14:30 UTC, Tbaut reviewed
This looks great!! I've a couple small changes that I'll push, like for the WalletConnect icon.

Also the links to setting > watched account need to be modified in the home page (and maybe some other places?) with the `#panel-watched-accounts`. This should make the Cypress test pass, or get us closer to.

2023-09-22 14:30 UTC, Tbaut commented on packages/ui/src/pages/Settings/WatchedAccounts.tsx
> +                    <AccountCountStyled>{index + 1}</AccountCountStyled>
Sorry that I didn't see this before in the design, but this is not needed, as it takes space and doesn't add value.
```suggestion
                    <AccountCountStyled>{index + 1}</AccountCountStyled>
```

2023-09-22 14:59 UTC, Lykhoyda commented on packages/ui/src/pages/Settings/Settings.tsx
> +  const handleChange = (panel: string) => (event: SyntheticEvent | null, isExpanded: boolean) => {
Wrapped in callback. I'm not sure about simplifying the methods as we have it as a callback from Accordion

```js
onChange?: (event: React.SyntheticEvent, expanded: boolean) => void;
```
it's also an example from the documentation, so if something is not clear there are more details by the link https://mui.com/material-ui/react-accordion/#system-ControlledAccordions.tsx

2023-09-22 15:01 UTC, Lykhoyda commented on packages/ui/src/pages/Settings/Settings.tsx
> +  const [expanded, setExpanded] = useState<string | false>(false)
I think we could be more precise as we can have the name of the accordion, which corresponds to a true or a collapsed boolean state.

2023-09-22 15:08 UTC, Lykhoyda commented on packages/ui/src/pages/Settings/Settings.tsx
> +  const [expanded, setExpanded] = useState<string | false>(false)
Created a type of strings

2023-09-22 15:34 UTC, Lykhoyda commented
> This looks great!! I've a couple small changes that I'll push, like for the WalletConnect icon. I'll do it later today.
> 
> The links to setting > watched account need to be modified in the home page (and maybe some other places?) with the `#panel-watched-accounts`. This should make the Cypress test pass, or get us closer to.

We need to add click on accordion for cypress test as before the inputs appeared right away.

2023-09-22 15:36 UTC, Lykhoyda commented
@asnaith @Tbaut please take a look again. I fixed the comments, let me know if i missed something

2023-09-22 16:29 UTC, Tbaut requested changes

2023-09-22 16:29 UTC, Tbaut commented on packages/ui/src/pages/Settings/WatchedAccounts.tsx
> +  const hasWatchedAddresses = useCallback(() => watchedAddresses.length > 0, [watchedAddresses])
This should be a `useMemo`

2023-09-22 16:29 UTC, Tbaut commented on packages/ui/src/pages/Settings/WatchedAccounts.tsx
> +      {hasWatchedAddresses() && (
then `hasWatchedAddresses` without needing to call it.

2023-09-22 16:29 UTC, Tbaut commented on packages/ui/src/pages/Settings/WatchedAccounts.tsx
> +        {hasWatchedAddresses() && (
same here.

2023-09-22 16:29 UTC, Tbaut commented on packages/ui/src/components/WalletConnect/WalletConnectSession.tsx
> +import React, { useCallback, useMemo, useState } from 'react'
No need for this.

2023-09-22 16:30 UTC, asnaith commented
> @asnaith @Tbaut please take a look again. I fixed the comments, let me know if i missed something

@Lykhoyda Those updates for the labels look good 👍

> We need to add click on accordion for cypress test as before the inputs appeared right away.

If you can update the link for the button below to use settings#watched-acccounts then it's going to be expanded when arriving on that screen and will be better for users and also no need to update the test

![CleanShot 2023-09-22 at 17 27 29@2x](https://github.com/ChainSafe/Multix/assets/3982665/948e1268-c22f-4c14-b06a-5c93952e2da6)

2023-09-24 22:01 UTC, Tbaut commented on packages/ui/src/pages/Settings/Settings.tsx
> +  const handleChange = (panel: string) => (event: SyntheticEvent | null, isExpanded: boolean) => {
Changed it in my PR. This was definitely needlessly complex :man_shrugging:

2023-09-24 23:31 UTC, Tbaut commented
I pushed some change to
- change a pit the logic to force open only the watched-account section if needed.
- optimize the WC SVG that took a while to load
- make the tests pass. Please check it out. We won't merge any PR that doesn't pass the test, unless it's due to flakiness (not the case here).

There are still a couple comments above that weren't taken into account yet, but it should be quick.

2023-09-25 13:03 UTC, Tbaut approved these changes
awesome, this looks a million time better. Thank you!

2023-09-25 13:06 UTC, merged