Autorefresh for tx so that pure and new msigs apprear without a manual refresh
ChainSafe/Multix pull request #529
Opened 2024-04-11 10:27 UTC by Tbaut

After implementing polling, unlike subscriptions, we now have to poll (for 1min) after certain transactions to make sure the UI auto-refreshes.

2024-04-11 15:52 UTC, Tbaut commented
Somehow the even extrinsic success isn't fired.. I'll ask the chopsticks team.
```
Transaction status: Ready
useSigningCallback.tsx:22 Transaction status: Broadcast
useSigningCallback.tsx:22 Transaction status: Finalized
useSigningCallback.tsx:87 Finalized block hash 0xdfd2e17fe46defa98bfc6b6e438de0530b241075593bbfa5fe8fe69b48e9a26f
```

2024-04-12 05:33 UTC, asnaith requested changes
I'm seeing some UI glitchiness (I've tried Chrome and Firefox) that persists even after a hard refresh. 

No errors are shown in the console when this happens. 

https://github.com/ChainSafe/Multix/assets/3982665/fda675de-9abd-4fee-857c-cea422d06db1

2024-04-12 07:43 UTC, Tbaut commented
This ias What happens in tests as well that I can't reproduce. I'll manage

2024-04-12 17:53 UTC, Tbaut commented
Thanks @asnaith it should be fixed now.

2024-04-12 20:44 UTC, asnaith commented on packages/ui/cypress/tests/multisig-creation.cy.ts
> +    it.only('Create a multisig with a pure proxy', () => {
```suggestion
    it('Create a multisig with a pure proxy', () => {
```

2024-04-12 20:49 UTC, asnaith approved these changes
Yep, all looking good now. No need for any hard refreshes. 

I added a small commit to remove a `it.only`

2024-04-12 22:21 UTC, Tbaut commented
Ah thanks, there's still quite some cleanup to do in this PR, I left some log and comments.

2024-04-15 09:44 UTC, merged